services:
  - type: web
    name: jio-arriendos
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py runserver 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: JIO.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False

